//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaketballGameSimulator2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametars_table
    {
        public Nullable<int> EfficiancyRaiseMinimum { get; set; }
        public Nullable<int> EfficiancyRaiseMaximum { get; set; }
        public Nullable<int> EfficiancyDeclineMinimum { get; set; }
        public Nullable<int> EfficiancyDeclineMaximum { get; set; }
        public Nullable<int> MinimalAgeForDraft { get; set; }
        public Nullable<int> MinimalAllowedEfficiancy { get; set; }
        public Nullable<int> MaximumAllowedEfficiancy { get; set; }
        public Nullable<float> EmotionalConst { get; set; }
        public Nullable<float> PhysicalConst { get; set; }
        public Nullable<float> IntellectuallConst { get; set; }
        public Nullable<float> DailyStatus { get; set; }
        public int Primary_id { get; set; }
    }
}
