//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaketballGameSimulator2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_of_players_table
    {
        public int Position_id { get; set; }
        public string Position { get; set; }
    }
}
