//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaketballGameSimulator2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamsinfo
    {
        public int Team_id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Coach { get; set; }
        public string Manager { get; set; }
        public string Owner { get; set; }
        public int EstablishmentDate { get; set; }

        

    }
}
